#:schema node_modules/wrangler/config-schema.json
name = "nodejs-compat-process"
main = "src/index.js"
compatibility_date = "2024-12-24"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[ai]
binding = "AI"
